apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: git-projects
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/aidaikin91/git_projects
  ref:
    branch: main
